version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install -g typescript
      - npm install -g mocha
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
      - npm run test
      - npm prune --production
  post_build:
    commands:
      - zip -r application.zip ./src
      - echo Build completed on `date`
artifacts:
  files:
    - application.zip
    - template.yml
    - dist/**/*
    - package.json
    - package-lock.json
