AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  AppGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: 'Pallas-Api-AppGateway'
      EndpointConfiguration: REGIONAL
      StageName: api
      Cors:
        AllowMethods: "'GET,PUT,POST,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date'"
        AllowCredentials: "'true'"
      GatewayResponses:
        Default:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Method: "'GET,PUT,POST,DELETE,OPTIONS'"
              Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date'"
              Access-Control-Allow-Origin: "'https://milesbb.tech'"
  
  AppLogGroup:
    Type: "AWS::Logs::LogGroup"
    DeletionPolicy: Retain
    Properties:
      LogGroupName: "/aws/lambda/PallasLambda"

  PallasExpressFunction:
    Type: AWS::Serverless::Function
    DeletionPolicy: Delete
    Properties:
      CodeUri: application.zip
      Runtime: nodejs14.x
      Description: "PallasLambda"
      FunctionName: "PallasLambda"
      Handler: dist/pallas_lambda
      MemorySize: 256
      PackageType: "Zip"
      Role: arn:aws:iam::442090781375:role/api-lambda-role
      Runtime: "provided"
      Timeout: 30
      Events:
        ProxyApiRoot:
          Type: Api
          Properties:
            RestApiId: !Ref AppGateway
            Path: /api
            Method: ANY